# Github workflow file to execute the docker-compose file (stored in project root) which will
# build the docker image (From the dockerfile) after establishing a required postgres image for successful build.
# The workflow then pushes the built image to dockerhub.
# Publish.yml and docker-compose.yml not used to deployment of live instance to Render.com (only dockerfile at project root)
name: Create and publish a Docker image
on:
  push:
    branches: [ 'docker' ]

jobs:
  build-and-publish-eatsy-api-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to the Docker Container registry
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}} #GITHUB secrets
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      - name: Build with Gradle for jar creation
        run: |
          ./gradlew clean build

      - name: Build and push the eatsy-api-docker Docker image
        run: |
          docker-compose up -d
          docker push ${{secrets.DOCKER_USER}}/eatsy-api-docker